#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zerobin"
name = "Zerobin"
description.en = "Minimalist pastebin where the server has zero knowledge of pasted data"
description.fr = "Pastebin minimaliste où le serveur n'a aucune connaissance des données copiées"

version = "1.7.1~ynh1"

maintainers = []

[upstream]
license = "Zlib"
website = "https://privatebin.info/"
demo = "https://privatebin.net/"
admindoc = "https://github.com/PrivateBin/PrivateBin/wiki"
code = "https://github.com/PrivateBin/PrivateBin"

[integration]
yunohost = ">= 4.3.0"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/zerobin"

    [install.init_main_permission]
    help.en = "If private, only YunoHost users can create a paste, but everyone can read it."
    help.fr = "Si privé, seul les utilisateurs YunoHost peuvent créer un paste, mais tout le monde peut lire."
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/PrivateBin/PrivateBin/archive/refs/tags/1.7.1.tar.gz"
        sha256 = "136faa5ba0c2d51ace916a2c0b282f5c7d5376265406040c91730e28233367ff"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.2 php8.2-gd"
