#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zerobin"
name = "Zerobin"
description.en = "Pastebin where the server has zero knowledge of pasted data"
description.fr = "Pastebin où le serveur ignore les données copiées"

version = "1.7.6~ynh1"

maintainers = []

[upstream]
license = "Zlib"
website = "https://privatebin.info/"
demo = "https://privatebin.net/"
admindoc = "https://github.com/PrivateBin/PrivateBin/wiki"
code = "https://github.com/PrivateBin/PrivateBin"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/zerobin"

    [install.init_main_permission]
    help.en = "If private, only YunoHost users can create a paste, but everyone can read it."
    help.fr = "Si privé, seul les utilisateurs YunoHost peuvent créer un paste, mais tout le monde peut lire."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/PrivateBin/PrivateBin/archive/refs/tags/1.7.6.tar.gz"
    sha256 = "4f886854cc45b42d0dfac874fcbc0a47fba4318d16d92e7ddb0c1b6666bdfb96"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.3, php8.3-gd"
