test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.eb58fc62.name = "Upgrade from 1.3.5~ynh2"