#!/bin/bash

source /usr/share/yunohost/helpers
source ./_common

# Retrieve arguments
domain=$1
path=$2
is_public=$3

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a zerobin
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Remove trailing "/" for next commands
if [[ ! "$path" == "/" ]]; then
    path=${path%/}
fi

# Copy files to the right place
final_path=/var/www/zerobin
sudo mkdir -p $final_path
extract_source $final_path

# Files owned by root, www-data can just read
sudo find $final_path -type f | xargs sudo chmod 644
sudo find $final_path -type d | xargs sudo chmod 755
sudo chown -R root: $final_path

# except for data and tmp subdir, where www-data must have write permissions
sudo mkdir -p $final_path/{data,tmp}
sudo chown -R www-data:root $final_path/{data,tmp}
sudo chmod 700 $final_path/{data,tmp}

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
nginxconf=/etc/nginx/conf.d/$domain.d/zerobin.conf
sudo cp ../conf/nginx.conf $nginxconf
sudo chown root: $nginxconf
sudo chmod 600 $nginxconf

sudo yunohost app setting zerobin is_public -v "$is_public"
if [ "$is_public" = "Yes" ];
then
  sudo yunohost app setting zerobin unprotected_uris -v "/"
fi

sudo service nginx reload
sudo yunohost app ssowatconf
