#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -u

# Source app helpers
source /usr/share/yunohost/helpers
source ./_common

# Get multi-instances specific variables
app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$(ynh_app_setting_get "$app" domain)

ynh_secure_rm /var/www/$app
ynh_secure_rm /etc/nginx/conf.d/$domain.d/$app.conf

sudo systemctl reload nginx